# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SazTools < Formula
  desc "Parsing, dumping, viewing and analysing tools for SAZ (Fiddler) files"
  homepage "https://github.com/prantlf/saz-tools"
  version "0.0.17"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/prantlf/saz-tools/releases/download/v0.0.17/saz-tools_0.0.17_darwin_x86_64.tar.gz"
    sha256 "a9dec376305202fd7865839e9687ff8d5ab5ec4e2cc0db9e3b8156c6dd1ddacb"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/prantlf/saz-tools/releases/download/v0.0.17/saz-tools_0.0.17_darwin_arm64.tar.gz"
    sha256 "ffbd70d9d387a9c0f64db8cb1fe14175429d2d5904049353947d7b86613a181e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/prantlf/saz-tools/releases/download/v0.0.17/saz-tools_0.0.17_linux_x86_64.tar.gz"
    sha256 "bb89f24fd0abaef5757b7ed048a013e5d2ed0ce114e144f3923a568cc62beee1"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/prantlf/saz-tools/releases/download/v0.0.17/saz-tools_0.0.17_linux_armv6.tar.gz"
    sha256 "6e624d6af37bbcb29f53a11f7c842db4e1fd03c3e7fc7086fd4671d0955f8e9e"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/prantlf/saz-tools/releases/download/v0.0.17/saz-tools_0.0.17_linux_arm64.tar.gz"
    sha256 "b61d06759c0f333df520b28a01e9db21a227ed69297686d3259a3f321fc19571"
  end

  def install
    bin.install "sazdump"
    bin.install "sazserve"
    man1.install "man/sazdump.1"
    man1.install "man/sazserve.1"
  end

  test do
    system "#{bin}/sazdump", "-v"
    system "#{bin}/sazserve", "-v"
  end
end
