# This file was generated by GoReleaser. DO NOT EDIT.
class SazTools < Formula
  desc "Tools for SAZ files (Fiddler logs) - parsing, printing and analyzing using a web page."
  homepage "https://github.com/prantlf/saz-tools"
  version "0.0.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/prantlf/saz-tools/releases/download/v0.0.9/saz-tools_0.0.9_darwin_x86_64.tar.gz"
    sha256 "bf2a067d599856f3a55107423c309cd7f352f4affc5ee64746677b8ff7eacb2f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/prantlf/saz-tools/releases/download/v0.0.9/saz-tools_0.0.9_linux_x86_64.tar.gz"
      sha256 "11c8bd477f2698f989e26e5cd18d9cf5bb41962b1ddc2ec8b5e47e6c078f071a"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/prantlf/saz-tools/releases/download/v0.0.9/saz-tools_0.0.9_linux_arm64.tar.gz"
        sha256 "ea8b18434bde3e37bc4de14b741d882416663d9eb4fdf74c0ef87b9651624e95"
      else
        url "https://github.com/prantlf/saz-tools/releases/download/v0.0.9/saz-tools_0.0.9_linux_armv6.tar.gz"
        sha256 "cc8346b32cfd87095ff52ab7762343e35c4dfa9a34af88a66384ef8a197b560f"
      end
    end
  end

  def install
    bin.install "sazdump"
    bin.install "sazserve"
  end

  test do
    system "#{bin}/sazdump -h"
    system "#{bin}/sazserve -h"
  end
end
