# This file was generated by GoReleaser. DO NOT EDIT.
class SazTools < Formula
  desc "Parsing, dumping, viewing and analysing tools for SAZ (Fiddler) files"
  homepage "https://github.com/prantlf/saz-tools"
  version "0.0.10"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/prantlf/saz-tools/releases/download/v0.0.10/saz-tools_0.0.10_darwin_x86_64.tar.gz"
    sha256 "847ac164e2e313cd3de0880c472a58773f8dcb601ffce38e7ef3469a4faaffad"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/prantlf/saz-tools/releases/download/v0.0.10/saz-tools_0.0.10_linux_x86_64.tar.gz"
      sha256 "592220c35483b3af4eeca80e0cacb82da25c6d4d404f203d6f9337c0476b1beb"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/prantlf/saz-tools/releases/download/v0.0.10/saz-tools_0.0.10_linux_arm64.tar.gz"
        sha256 "e512a947409d61d1b2f9d367202f2c1725e450c97f6e2f200db8adb67a0cbc8d"
      else
        url "https://github.com/prantlf/saz-tools/releases/download/v0.0.10/saz-tools_0.0.10_linux_armv6.tar.gz"
        sha256 "a59bf1b2cc8229f7ea23a03f1671cdd9513b72294df9776062cfab4eacca259b"
      end
    end
  end

  def install
    bin.install "sazdump"
    bin.install "sazserve"
    man1.install "man/sazdump.1"
    man1.install "man/sazserve.1"
  end

  test do
    system "#{bin}/sazdump", "-v"
    system "#{bin}/sazserve", "-v"
  end
end
